language: objective-c
osx_image: xcode7.3
xcode_project: ELog
xcode_scheme: ELog
xcode_sdk: iphonesimulator9.3
env:
  global: 
    - FRAMEWORK_NAME=ELExport
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
